name: LuxS2
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - black
  - nvidia::cuda-nvcc=11.7
  - nvidia::cuda-toolkit=11.7
  - isort
  - jax
  - matplotlib
  - pytest
  - pytorch
  - pytorch-cuda=11.7
  - ray-tune
  - setuptools<=65.5.0
  - snakeviz
  - tensorboard
  - tqdm
  - pip
  - pip:
      - juxai_s2
      - luxai_s2
