name: LuxS2
channels:
  - conda-forge
dependencies:
  - black
  - isort
  - jax
  - matplotlib
  - pytest
  - python=3.8
  - setuptools<=65.5.0
  - tqdm
  - pip
  - pip:
      - dm-haiku
      - luxai-s2
      - juxai-s2
      - optax
      - rlax
      - numpy>=1.24
